name: Stock Scanner

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Run scanner
      run: |
        python scanner.py
    
    - name: Commit and push results
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add results/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update scan results - $(date +'%Y-%m-%d %H:%M:%S')" && git push)
